### PR TITLE
Sync debounce fix and test

### PR DESCRIPTION
**Pull request by wifisher**
Updated the countdown timer restart() method to accept an optional newDurationMs parameter which will change the countdown timer duration.

Update the batchSync triggerSync() method to use the newDurationMs parameter. It is set to the syncDebounceMs value.

Added some timing tests to confirm that the action's syncDebounceMs value is used and works as expected. That is, the most recent syncDebounceMs value is the one used.

### CODE REVIEW

**Comment by mesqueeb** [comment]
@wifisher thank you so much. I will look into this pr this week

**Comment by wifisher** [comment]
Do you know when you might get a chance to look at this PR?

Most of the changes are in the new tests. The changes to the Firestore plugin are relatively small.

**Comment by mesqueeb** [comment]
@wifisher thank you for reminding me. Happy New year !

Things got a little hectic for me near end year. 

I should be able to find timethis weekend to merge and also add the license.

**Comment by mesqueeb** [comment]
@wifisher Thank you very much for the PR.

The Firestore tests running against an actual server with actual API calls was something that was always a bit flaky and I meant to improve ages ago.

Finally got around spending all morning to make sure the tests run against the Firestore emulators.
Sure enough, now all your tests added succeed! Thanks !! ;)

**Pull request merged**
